#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
slide_select_byCluster.py

Select representative patch coordinates from per-WSI clustering results.

Input
-----
Cluster assignment text files generated by featureClustering_dino.py, typically:
    *_kmeans_cls.txt

Each line is expected to be:
    (x, y)\tcluster_id

Workflow
--------
For each WSI:
1. group patch coordinates by cluster
2. shuffle coordinates within each cluster
3. determine the maximum cluster size
4. compute how many selection rounds are needed:
       ceil(max_cluster_count / num_per_cls)
5. for every cluster, repeat coordinates if needed so that each round can
   still sample `num_per_cls` patches
6. write one selection txt per round

Output
------
For each WSI, multiple txt files are written:
    <wsi>kmeans_cls_0.txt
    <wsi>kmeans_cls_1.txt
    ...

Each output txt contains `cls_num` rows and `num_per_cls` columns in tab-separated format.
Each row corresponds to one cluster and stores selected patch coordinates.

Notes
-----
This script preserves the original selection logic and output style used by the
downstream feature-writing workflow.
"""

import argparse
import glob
import math
import os
from typing import Dict, List

import openslide
import pandas as pd
import numpy as np


RNG = np.random.RandomState(0)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Select patch coordinates from per-WSI clustering results."
    )
    parser.add_argument(
        "--txt_path",
        default="/Pathology_data/UCEC/ucec_all_dino_feat_clustering",
        type=str,
        help="Directory containing cluster assignment txt files.",
    )
    parser.add_argument(
        "--txt_res_path",
        default="/Pathology_data/UCEC/ucec_whole_slide_select_txt_dino",
        type=str,
        help="Output directory for selected patch coordinate txt files.",
    )
    parser.add_argument(
        "--cls_num",
        default=50,
        type=int,
        help="Number of clustering classes.",
    )
    parser.add_argument(
        "--num_per_cls",
        default=10,
        type=int,
        help="Number of patches selected per cluster in each selection round.",
    )

    # Kept for optional patch extraction utility
    parser.add_argument(
        "--wsi_path",
        default="",
        type=str,
        help="Optional root directory of WSI files (.svs), used only by cut_img().",
    )
    parser.add_argument(
        "--img_path",
        default="",
        type=str,
        help="Optional output directory for extracted patch images, used only by cut_img().",
    )

    return parser


def get_wsi_path(args: argparse.Namespace, txt_name: str) -> str:
    """
    Infer WSI path from clustering txt file name.

    Original logic:
    - identify substring before 'kmean'
    - append '.svs'
    - join with args.wsi_path
    """
    dir_pos = txt_name.find("kmean")
    if dir_pos == -1:
        raise ValueError(f"Cannot infer WSI name from txt file: {txt_name}")
    wsi_path = os.path.join(args.wsi_path, txt_name[:dir_pos] + ".svs")
    return wsi_path


def cut_img(args: argparse.Namespace, path: str, ext: str, coords: List[str]) -> None:
    """
    Optional utility: cut patch images from a WSI using selected coordinates.

    This helper is preserved from the original script but is not called in the
    main selection workflow.
    """
    if not args.wsi_path:
        raise ValueError("--wsi_path is required when using cut_img().")
    if not args.img_path:
        raise ValueError("--img_path is required when using cut_img().")

    img_size = 768
    txt_name = os.path.basename(path)
    wsi_path = get_wsi_path(args, txt_name)

    slide = openslide.open_slide(wsi_path)
    img_name = os.path.basename(wsi_path[:-4])
    img_dir = os.path.join(args.img_path, img_name + "_" + str(ext))
    os.makedirs(img_dir, exist_ok=True)

    print(f"Cutting patches from {wsi_path}")
    if len(coords) != args.cls_num:
        raise ValueError(
            f"Wrong number of patch groups: got {len(coords)}, expected {args.cls_num}"
        )

    count_num = 0
    for coord in coords:
        count_num += 1
        coord_split = coord.split(",")
        x = int(coord_split[0][1:])
        y = int(coord_split[1][:-1])
        img = slide.read_region((x * img_size, y * img_size), 1, (img_size, img_size)).convert("RGB")
        out_name = f"{img_name}_{x}_{y}_{count_num}.png"
        img.save(os.path.join(img_dir, out_name))


def parse_cluster_file(path: str) -> Dict[int, List[str]]:
    """
    Parse one clustering result txt file.

    Expected format per line:
        (x, y)\tcluster_id
    """
    cluster_to_coords: Dict[int, List[str]] = {}

    with open(path, "r") as f:
        for raw_line in f:
            line = raw_line.strip()
            if not line:
                continue

            parts = line.split("\t")
            if len(parts) < 2:
                raise ValueError(f"Malformed line in {path}: {line}")

            coord = parts[0]
            cls_id = int(parts[1])

            if cls_id in cluster_to_coords:
                cluster_to_coords[cls_id].append(coord)
            else:
                cluster_to_coords[cls_id] = [coord]

    return cluster_to_coords


def ensure_all_clusters_present(
    cluster_to_coords: Dict[int, List[str]],
    cls_num: int,
    path: str,
) -> None:
    """
    Ensure all cluster IDs [0, cls_num-1] are present.

    The original script implicitly assumed this. Here we keep the same
    expectation but make failure explicit.
    """
    missing = [i for i in range(cls_num) if i not in cluster_to_coords]
    if missing:
        raise ValueError(
            f"{path}: missing cluster ids {missing}. "
            f"Expected all cluster ids in [0, {cls_num - 1}]."
        )


def repeat_if_needed(
    values: List[str],
    required_len: int,
) -> List[str]:
    """Repeat a coordinate list until it reaches the required length."""
    if len(values) == 0:
        raise ValueError("Encountered an empty cluster; cannot repeat empty coordinate list.")
    if len(values) >= required_len:
        return values

    repeat_count = math.ceil(required_len / len(values))
    expanded = values * repeat_count
    return expanded


def run(args: argparse.Namespace) -> None:
    os.makedirs(args.txt_res_path, exist_ok=True)

    paths = sorted(glob.glob(os.path.join(args.txt_path, "*.txt")))
    if len(paths) == 0:
        print(f"[WARN] No txt files found under: {args.txt_path}")
        return

    for path in paths:
        print(path)

        basename = os.path.basename(path)
        cluster_to_coords = parse_cluster_file(path)
        ensure_all_clusters_present(cluster_to_coords, args.cls_num, path)

        max_cluster_count = max(len(cluster_to_coords[idx]) for idx in range(args.cls_num))
        max_cluster_iters = math.ceil(max_cluster_count / args.num_per_cls)

        # Deterministic shuffle within each cluster
        for key in cluster_to_coords:
            RNG.shuffle(cluster_to_coords[key])

        print(f"Max cluster count is {max_cluster_count}.")

        # If a cluster is too small, repeat coordinates so every round can still
        # provide num_per_cls patches.
        required_len = max_cluster_iters * args.num_per_cls
        for key, values in cluster_to_coords.items():
            cluster_to_coords[key] = repeat_if_needed(values, required_len)

        # One output txt per round
        for i in range(max_cluster_iters):
            coords = []
            start = i * args.num_per_cls
            end = (i + 1) * args.num_per_cls

            for key in range(args.cls_num):
                choice_coord = cluster_to_coords[key][start:end]
                coords.append(choice_coord)

            data = pd.DataFrame(coords)
            out_name = basename.replace(".txt", f"_{i}.txt")
            out_path = os.path.join(args.txt_res_path, out_name)
            data.to_csv(out_path, sep="\t", index=False, header=False)


def main() -> None:
    args = build_parser().parse_args()
    run(args)


if __name__ == "__main__":
    main()
